#!/usr/bin/env bash

# Promps for input, returns true if response is a variant of yes and returns false if it isn't. Can accept a string for input prompt dialogue
function isyes {
  if [ ! -z "$1" ]; then
    read -p "$1 " ANSWER
  else
    read ANSWER
  fi
  if [ -z "$ANSWER" ]; then
    ANSWER="y"
  fi
  if [ $ANSWER == y ] || [ $ANSWER == Y ] || [ $ANSWER == yes ] || [ $ANSWER == Yes ] || [ $ANSWER == YES ]; then
    yes=0 && return 0
  else
    yes=1 && return 1
  fi
}

# Takes input in the form of an array, and checks each array item against user input.
# Returns true if a match is found and false if the response does not exist in the input array.
# User input is stored in $RESPONSE.
#
# Syntax: isvalidresponse "${INPUTARRAY[@]}"
#
function isvalidresponse {
  read RESPONSE
  if [ -z "$RESPONSE" ]; then
    RESPONSE="NULL"
  fi
  for i in "${@}"; do
    if echo "$i" | grep $RESPONSE &> /dev/null; then
      return 0
    else
      false
    fi
  done
}

# Executes input from $1 once, then repeats as long as isvalidresponse returns false.
# syntax: untilvalidresponse 'echo foo; echo bar' "${INPUTARRAY[@]}"
#
function untilvalidresponse {
  eval "$1"
  until isvalidresponse "${@:2}"; do
    ctext magenta std "Invalid response!"
    eval "$1"
  done
}

# Tests network connectivity, returning false when the user does not answer yes to retry or after 10 seconds if $1 is --noretry.
# Returns true if wget is succesful in the beginning or during the 10 second count.
#
function nettest {
  ctext cyan std "Testing internet connection"
  until ping 8.8.8.8 -c 1 &> /dev/null; do
    COUNT="0"
    until [ $COUNT == 10 ]; do
      echo "."
      sleep 1
      COUNT=$((COUNT + 1))
      if ping 8.8.8.8 -c 1 &> /dev/null; then
        return 0
      fi
    done
    ctext magenta std "Network unreachable after 10 seconds!"
    sleep 0.5
    if [ "$1" == --noretry ]; then
      return 1
    else
      if ! isyes "$(ctext cyan nnl "Retry? (Y/n)")"; then
        return 1
      fi
    fi
  done
}

# Executes input operations once, then repeats them until nettest passes.
# Syntax: untilnetpass 'echo foo; echo bar'
#
function untilnetpass {
  eval "$@"
  until nettest; do
    eval "$@"
  done
}

# Use to add colour to dialogue text.
# Syntax: ctext somecolour texttype 'some random text'
#
function ctext {
  # Set colour from $1
  if [ "$1" == black ]; then
    tput setaf 0
  fi
  if [ "$1" == red ]; then
    tput setaf 1
  fi
  if [ "$1" == green ]; then
    tput setaf 2
  fi
  if [ "$1" == yellow ]; then
    tput setaf 3
  fi
  if [ "$1" == blue ]; then
    tput setaf 4
  fi
  if [ "$1" == magenta ]; then
    tput setaf 5
  fi
  if [ "$1" == cyan ]; then
    tput setaf 6
  fi
  if [ "$1" == white ]; then
    tput setaf 7
  fi
  if [ "$1" == reset ]; then
    tput sgr 0
  fi
  # text method from $2
  if [ "$2" == std ]; then
    echo "${@:3}"
    tput sgr 0
  fi
  if [ "$2" == nnl ]; then
    echo -n "${@:3}"
    tput sgr 0
  fi
  if [ "$2" == std,nres ]; then
    echo "${@:3}"
  fi
  if [ "$2" == nnl,nres ]; then
    echo -n "${@:3}"
  fi
}
